FROM golang:1.11
WORKDIR /go/src/github.com/astota/go-logging

COPY . .
RUN go get -u github.com/golang/dep/cmd/dep && go install github.com/golang/dep/cmd/dep
RUN dep ensure -v

RUN go test -v -race
